version: "3"

x-common-variables: &global-variables
  REDIS_URL_SIDEKIQ: redis://redis:6379/1

services:
  web:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - "~/.ssh/:/.ssh"
      - "./docker/dev/database.yml:/app/config/database.yml"
      - bundler_gems:/usr/local/bundle/
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    environment:
      <<: *global-variables
  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sequra_backend_challenge
    expose:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
      - "./docker/dev/setup_database.sh:/usr/local/bin/setup_database.sh"
  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'
  sidekiq:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec sidekiq"
    volumes:
      - .:/app
      - bundler_gems:/usr/local/bundle/
    depends_on:
      - db
      - redis
    stdin_open: true
    tty: true
    environment:
      <<: *global-variables
volumes:
  redis:
  bundler_gems:
  db:
    driver: local
